### ISSUE TITLE
"memcpy" was not declared in this scope

### ISSUE THREAD

**Issue by JacomusP** [torch/rnn#45]
When I try to install rnn with luarocks with the following command: "luarocks install rnn" I get the following error.

/usr/include/string.h: In function ‘void* __mempcpy_inline(void*, const void*, size_t)’:
/usr/include/string.h:652:42: error: ‘memcpy’ was not declared in this scope
   return (char *) memcpy (__dest, __src, __n) + __n;

All of the output from the command is below:

Installing https://raw.githubusercontent.com/torch/rocks/master/rnn-scm-1.rockspec...
Using https://raw.githubusercontent.com/torch/rocks/master/rnn-scm-1.rockspec... switching to 'build' mode
Cloning into 'rnn'...
remote: Counting objects: 183, done.
remote: Compressing objects: 100% (155/155), done.
remote: Total 183 (delta 28), reused 98 (delta 19), pack-reused 0
Receiving objects: 100% (183/183), 903.53 KiB | 0 bytes/s, done.
Resolving deltas: 100% (28/28), done.
Checking connectivity... done.
cmake -E make_directory build;
cd build;
cmake .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_PREFIX_PATH="/home/jacomus/torch/install/bin/.." -DCMAKE_INSTALL_PREFIX="/home/jacomus/torch/install/lib/luarocks/rocks/rnn/scm-1" -DCMAKE_C_FLAGS=-fPIC -DCMAKE_CXX_FLAGS=-fPIC;
make
   
-- The C compiler identification is GNU 5.4.0
-- The CXX compiler identification is GNU 5.4.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found Torch7 in /home/jacomus/torch/install
-- Found CUDA: /usr (found suitable version "7.5", minimum required is "6.5") 
-- Automatic GPU detection failed. Building for common architectures.
-- Autodetected CUDA architecture(s): 3.0;3.5;5.0;5.2;5.2+PTX
-- Configuring done
-- Generating done
-- Build files have been written to: /tmp/luarocks_rnn-scm-1-7762/rnn/build
[ 14%] Building NVCC (Device) object CMakeFiles/rnn.dir/src/rnn_generated_rnn.cu.o
/usr/include/string.h: In function ‘void* __mempcpy_inline(void*, const void*, size_t)’:
/usr/include/string.h:652:42: error: ‘memcpy’ was not declared in this scope
   return (char *) memcpy (__dest, __src, __n) + __n;
                                          ^
CMake Error at rnn_generated_rnn.cu.o.cmake:267 (message):
  Error generating file
  /tmp/luarocks_rnn-scm-1-7762/rnn/build/CMakeFiles/rnn.dir/src/./rnn_generated_rnn.cu.o

CMakeFiles/rnn.dir/build.make:63: recipe for target 'CMakeFiles/rnn.dir/src/rnn_generated_rnn.cu.o' failed
make[2]: *** [CMakeFiles/rnn.dir/src/rnn_generated_rnn.cu.o] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/rnn.dir/all' failed
make[1]: *** [CMakeFiles/rnn.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by tastyminerals** [comment]
Might not be related but make sure you compile Torch with **gcc-4.9**.

**Comment by JacomusP** [comment]
How would I go about doing that without having to make everything be compiled with gcc-4.9?

**Comment by tastyminerals** [comment]
CUDA 7.5 is pretty dated, try with CUDA 8.0 or CUDA 9.0

**Comment by JacomusP** [comment]
Yea I noticed that. I actually install cuda 8 but somehow cuda 7.5 got installed. I will update it and let you know if that changed anything.

**Comment by JacomusP** [comment]
I installed cuda 9.1 and it installed fine. Thanks for your help.
